[package]
name = "client"
version = "0.1.0"
edition = "2024"

[dependencies]
async_runtime = { version = "0.1.0", path = "../async_runtime" }
data_layer = { version = "0.1.0", path = "../data_layer" }
