[package]
name = "ch09-design-patterns"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.47.1", features = [
    "rt",
    "macros",
    "rt-multi-thread",
    "time",
    "sync",
] }
uuid = { version = "1.18.0", features = ["v4"] }

[features]
logging_decorator = []
